### ISSUE TITLE
Building the site for tag v4.1.1 error

### ISSUE THREAD

**Issue by haies** [openlayers/openlayers.github.io#94]
It works when I built the site for latest version, however when i run the following script to build the site for tag v4.1.1 it didn't wors.
`
 treeish=v4.1.1 npm run deploy
`
And the output error is
`
Running "run:ol" (run) task
npm ERR! missing script: build-legacy
`
so, i checkout  Updating for v4.1.1 edition, then run above script,but it show the following error
`
Running "make:examples" (make) task
 info
ol Parsing dependencies
info
ol Compiling 345 sources
vents.js:183
throw er; // Unhandled 'error' event
`
My project already has used openlayers 4.1.1 for quite a long time, could anyone please show the righ way to build v4.1.1 docs  ?

**Comment by ahocevar** [comment]
You have to check out the correct revision of this repository before building the docs, i.e. 3c9f652c97776702eaa88f0849b0497a08d86bba:

    git checkout 3c9f652c97776702eaa88f0849b0497a08d86bba
    treeish=v4.1.1 npm run build

**Comment by haies** [comment]
@ahocevar Thanks a lot for taking the time to reply to my problem.
 I have tried the way you suggested,
But, I still got the following errors:

Running "make:examples" (make) task
\>\> info
\>\> ol Parsing dependencies
\>\> info
\>\> ol Compiling 345 sources
\>\> events.js:183
\>\>       throw er; // Unhandled 'error' event
\>\>       \^
\>\>
\>\> Error: spawn java ENOENT
\>\>     at _errnoException (util.js:992:11)
\>\>     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
\>\>     at onErrorNT (internal/child_process.js:372:16)
\>\>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
\>\>     at process._tickCallback (internal/process/next_tick.js:180:9)
\>\> make: * [build/ol.js] Error 1

Warning: make failure: 2 Use --force to continue.
And my enviroment is :

➜  openlayers.github.io lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.3 (stretch)
Release:        9.3
Codename:       stretch
➜  openlayers.github.io node -v
v8.11.3
➜  openlayers.github.io git --version
git version 2.11.0

**Comment by ahocevar** [comment]
It is also important to run `npm install` after checking out the required revision from this repository.

**Comment by haies** [comment]
I run the following script from the begaining:
`
git clone -b build https://github.com/openlayers/openlayers.github.io.git
cd openlayers.github.io
git pull origin build
git checkout 3c9f652c97776702eaa88f0849b0497a08d86bba
npm install
treeish=v4.1.1 npm run build
`
I got the same error as above, any other suggestions?
